config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  resources :reservas
  resources :produtos

  devise_for :users, controlers: {
    registrations: 'registrations'
  }

  root 'pages#home'
  
  get '/about', to: 'pages#about'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/reserva.rb
class Reserva < ApplicationRecord
  has_many :line_items, dependent: :destroy

  def add_produto(produto)
    current_item = line_items.find_by(produto_id: produto.id)
    if current_item
      current_item.increment(:quantity)
    else
      current_item = line_items.buil(produto_id: produto_id)
    end
    current_item
  end

  def preco_total
    line_items.to_a.sum { |item| item.preco_total }
  end
  
end

app/controllers/reservas_controller.rb
class ReservasController < ApplicationController
  rescue_from ActiveRecord: :RecordNotFound, with: :invalid_reserva
  before_action :set_reserva, only: [:show, :edit, :update, :destroy]

  # GET /reservas
  # GET /reservas.json
  def index
    @reservas = Reserva.all
  end

  # GET /reservas/1
  # GET /reservas/1.json
  def show
  end

  # GET /reservas/new
  def new
    @reserva = Reserva.new
  end

  # GET /reservas/1/edit
  def edit
  end

  # POST /reservas
  # POST /reservas.json
  def create
    @reserva = Reserva.new(reserva_params)

    respond_to do |format|
      if @reserva.save
        format.html { redirect_to @reserva, notice: 'Reserva foi criada com sucesso.' }
        format.json { render :show, status: :created, location: @reserva }
      else
        format.html { render :new }
        format.json { render json: @reserva.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservas/1
  # PATCH/PUT /reservas/1.json
  def update
    respond_to do |format|
      if @reserva.update(reserva_params)
        format.html { redirect_to @reserva, notice: 'Reserva was successfully updated.' }
        format.json { render :show, status: :ok, location: @reserva }
      else
        format.html { render :edit }
        format.json { render json: @reserva.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservas/1
  # DELETE /reservas/1.json
  def destroy
    @reserva.destroy if @reserva.id == session[:reserva_id]
    session[:reserva_id] = nil
    respond_to do |format|
      format.html { redirect_to reservas_url, notice: 'Reserva was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reserva
      @reserva = Reserva.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reserva_params
      params.fetch(:reserva, {})
    end

    def invalid_reserva
      logger.error "Tentativa de acessar uma reserva inválida #{params[:id]}"
      redirect_to root_path, notice: "Esta reserva não existe."
    end

end

app/helpers/reservas_helper.rb
module ReservasHelper
end

app/views/reservas/_form.html.erb
<%= simple_form_for(@reserva) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/reservas/edit.html.erb
<h1>Editing Reserva</h1>

<%= render 'form', reserva: @reserva %>

<%= link_to 'Show', @reserva %> |
<%= link_to 'Back', reservas_path %>

app/views/reservas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reservas</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reservas.each do |reserva| %>
      <tr>
        <td><%= link_to 'Show', reserva %></td>
        <td><%= link_to 'Edit', edit_reserva_path(reserva) %></td>
        <td><%= link_to 'Destroy', reserva, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reserva', new_reserva_path %>

app/views/reservas/new.html.erb
<h1>New Reserva</h1>

<%= render 'form', reserva: @reserva %>

<%= link_to 'Back', reservas_path %>

app/views/reservas/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_reserva_path(@reserva) %> |
<%= link_to 'Back', reservas_path %>