config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  resources :reservas
  resources :produtos

  devise_for :users, controlers: {
    registrations: 'registrations'
  }

  root 'pages#home'
  
  get '/about', to: 'pages#about'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/produto.rb
class Produto < ApplicationRecord

  before_destroy :not_referenced_by_any_line_item
  mount_uploader :image, ImageUploader
  serialize :image, JSON # Para o caso de usar SQLite
  belongs_to :user, optional: true
  has_many :line_items

  validates :nome, :preco, presence: true
  validates :descricao, length: { maximum: 1000, too_long: "%{count} caracteres é o tamanho máximo permitido." }
  validates :nome, length: { maximum: 140, too_long: "%{count} caracteres é o tamanho máximo permitido." }
  validates :preco, numericality: { only_integer: true },  length: { maximum: 7 }

  private

  def not_referenced_by_any_line_item
    unless line_items.empty?
      errors.add(:base, "Itens de pedido presentes")
      throw :abort
    end
  end

end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  before_action :set_produto, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]

  # GET /produtos
  # GET /produtos.json
  def index
    @produtos = Produto.all.where(disponibilidade: true)
  end

  # GET /produtos/1
  # GET /produtos/1.json
  def show
  end

  # GET /produtos/new
  def new
    @produto = Produto.new
    # @produto = current_user.produtos.build
  end

  # GET /produtos/1/edit
  def edit
    authorize! :manage, @product
  end

  # POST /produtos
  # POST /produtos.json
  def create
    @produto = current_user.produtos.build(produto_params)
    # @produto = current_user.produtos.new(produto_params)
    # @produto.image.attach(params[:image])
    # @produto.image.attached?

    respond_to do |format|
      if @produto.save
        format.html { redirect_to @produto, notice: 'Produto foi criado com sucesso.' }
        format.json { render :show, status: :created, location: @produto }
      else
        format.html { render :new }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /produtos/1
  # PATCH/PUT /produtos/1.json
  def update
    authorize! :manage, @product
    respond_to do |format|
      if @produto.update(produto_params)
        format.html { redirect_to @produto, notice: 'Produto atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @produto }
      else
        format.html { render :edit }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produtos/1
  # DELETE /produtos/1.json
  def destroy
    authorize! :manage, @product
    @produto.destroy
    respond_to do |format|
      format.html { redirect_to produtos_url, notice: 'Produto removido com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produto
      @produto = Produto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def produto_params
      params.require(:produto).permit(:nome, :descricao, :preco, :disponibilidade, :image)
    end
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/produtos/_form.html.erb
<div class="row">

  <div class="col-md-8">

    <%= simple_form_for @produto, html: { multipart: true } do |f| %>
      <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
    
        <div class="grupo-entrada">
          <%= f.input :nome, required: true, label: false, placeholder: 'Nome', wrapper: false, input_html: { class: "campo" } %>
        </div>

        <div class="grupo-entrada">
          <%= f.input :descricao, required: true, label: false, wrapper: false, placeholder: 'Descrição do produto' %>
        </div>
        
        <div class="grupo-entrada">
          <%= f.input :preco, required: true, label: false, wrapper: false, placeholder: 'Valor em centavos' %>
        </div>

        <div class="grupo-entrada">    
          <%= f.input :disponibilidade %>
        </div>

        <div class="form-group">
          <div class="grupo-entrada">
            <%= f.input :image, as: :file, input_html: { class: "form-control produto-image"}, label: false, wrapper: false %>
            <span class="file-cta">
              <span class="file-icon"><i class="fa fa-upload"></i></span>
              <span class="file-label">Escolha um arquivo</span>
            </span>
          </div>
          <output id="list"></output>
        </div>
        
        <div style="text-align: center; margin-top: 40px">
          <%= f.button :submit, input_html: {class: "btn btn-primary btn-block"} %>
        </div>
    <% end %>
  </div>
</div>

app/views/produtos/_produto.html.erb
<div class="col-md-3">
  <div>
      <%= image_tag "pop_gone_batty.jpg", class: 'img-fluid' %>
  </div>
  <div class="caption">
    
  </div>
</div>

app/views/produtos/edit.html.erb
<h1>Editar Produto</h1>

<div class="produtos">
  <%= render 'form', produto: @produto %>
</div>

<div class="row" style="padding: 10px;">
  <% if can? :update, Produto %>
    <div class="col-md-1">
      <%= link_to 'Exibir', @produto, class: 'btn btn-primary' %>
    </div>
    <div class="col-md-1">
      <%= link_to 'Voltar', produtos_path, class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/produtos/index.html.erb
<div class="card-columns">
  <%@produtos.each do |produto| %>
      <div class="card text-center bg-light mb-3">
        <div class="card-body">
            <%= link_to image_tag(produto.image_url(:thumb)), produto, html_input: {class: 'card-img-top img-thumbnail'} %>
            <div class="card-title">
              <%= link_to produto.nome, produto_path(produto), html_input: {class: 'card-title'} %>
            </div> 
            <div class="card-text">
              Teste
            </div>
        </div>
      </div>
  <% end %>
</div>

<div class="row" style="padding: 10px;">
  <% if can? :create, Produto %>
      <%= link_to 'Novo Produto', new_produto_path, class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/produtos/new.html.erb
<h1>Novo Produto</h1>

<div class="produtos">
  <%= render 'form', produto: @produto %>
</div>

<div class="row" style="padding: 10px;">
  <%= link_to 'Back', produtos_path, class: 'btn btn-primary' %>
</div>

app/views/produtos/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">
        <%= image_tag(@produto.image_url(:default)) %>
    </div>
    <div class="col-md-6">
      <div class="row justify-content-center" style="padding: 10px;">
        <div class="card bg-light">        
          <div class="card-body text-center">
            <h3 class="card-title"><%= @produto.nome %></h3>
            <p class="card-text"><%= @produto.descricao %></p>
            <p class="text-right"><%= number_to_currency(@produto.preco) %></p>
            <%= button_to  "Adicionar à reserva", line_item_path(produto_id: @produto), class: 'btn btn-primary btn-block' %>
          <div>        
        </div>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <div class="row" style="padding: 10px;">
    <% if can? :update, Produto %>
      <div class="col-md-1">
        <%= link_to 'Editar', edit_produto_path, class: 'btn btn-primary' %>
      </div>
      <div class="col-md-1">
        <%= link_to 'Voltar', produtos_path, class: 'btn btn-primary' %>
      </div>
    <% end %> 
  </div> 
</div>