config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  resources :reservas
  resources :produtos

  devise_for :users, controlers: {
    registrations: 'registrations'
  }

  root 'pages#home'
  
  get '/about', to: 'pages#about'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :produto
  belongs_to :reserva

  def preco_total
    produto.preco.to_i * quantity.to_i    
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  include CurrentReserva
  before_action :set_line_item, only: [:show, :edit, :update, :destroy]
  before_action :set_reserva, only: [:create]

  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items
  # POST /line_items.json
  def create
    produto = Produto.find(params[:produto_id])
    @line_item = @reserva.add_produto(produto)

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to @line_item.reserva, notice: 'Item adicionado à reserva.' }
        format.json { render :show, status: :created, location: @line_item }
      else
        format.html { render :new }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_items/1
  # PATCH/PUT /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to @line_item, notice: 'Line item was successfully updated.' }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @reserva = Reserva.find(session[:reserva_id])
    @line_item.destroy
    respond_to do |format|
      format.html { redirect_to reserva_path(@reserva), notice: 'Item da reserva foi removido com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_item_params
      params.require(:line_item).permit(:produto_id)
    end
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/_form.html.erb
<%= simple_form_for(@line_item) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.association :produto %>
    <%= f.association :reserva %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/line_items/edit.html.erb
<h1>Editing Line Item</h1>

<%= render 'form', line_item: @line_item %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Line Items</h1>

<table>
  <thead>
    <tr>
      <th>Produto</th>
      <th>Reserva</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.produto %></td>
        <td><%= line_item.reserva %></td>
        <td><%= link_to 'Show', line_item %></td>
        <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
        <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line Item', new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New Line Item</h1>

<%= render 'form', line_item: @line_item %>

<%= link_to 'Back', line_items_path %>

app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Produto:</strong>
  <%= @line_item.produto %>
</p>

<p>
  <strong>Reserva:</strong>
  <%= @line_item.reserva %>
</p>

<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>