config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  resources :reservas
  resources :produtos

  devise_for :users, controlers: {
    registrations: 'registrations'
  }

  root 'pages#home'
  
  get '/about', to: 'pages#about'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to root_path, class: "navbar-brand" do %>
    <i class="fas fa-gift"></i> Toys'R'Them
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" 
                                 data-target="#navbarSupportedContent"
                                 aria-controls="navbarSupportedContent"
                                 aria-expanded="false" 
                                 aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">      

      <% if user_signed_in? %>
        <span class="navbar-text">
          <strong><i class="fas fa-user-astronaut"></i> <%= current_user.email %></strong>
        </span>
        <li class="nav-item">
            <%= link_to 'Minha Conta', edit_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
            <%= link_to 'Sair', destroy_user_session_path, method: :delete, class: "nav-link" %>       
        </li>
      <% else %>
          <li class="nav-item">
            <%= link_to 'Login', new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sobre', about_path, class: "nav-link" %>
          </li>
      <% end %>   
      
      <li><%= link_to 'Minions', produtos_path, class: "nav-link" %></li>
    
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DesafioRafael</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <% flash.each do |type, message| %>
      <div class="alert alert-info fade-in">
        <button class = 'close' data-dismiss = "alert">X</button>
        <%= message %>
      </div>
    <% end %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>